### ISSUE TITLE
Report timer

### ISSUE THREAD

**Issue by jonorozcoc** [notiflix/Notiflix#10]
Can report modals have no button and autoclose timer?

**Comment by furcan** [comment]
Hi,

"No" button does not exist for the Report module. Also the Report elements does not remove until they were clicked. 

If you need a "No"(deny) button, may be you can use the Confirm module.

Thanks.

**Comment by jonorozcoc** [comment]
What I meant is if i can remove the button on Report

**Comment by furcan** [comment]
Hi again,

Your request has been noted.

The next update of the Notiflix may include this option for the Report Module. Stay in follow.

Thank you.
