### ISSUE TITLE
Report timeout

### ISSUE THREAD

**Issue by dingetje** [notiflix/Notiflix#11]
The timeout property is not working when I use a Report notify.

**Comment by furcan** [comment]
Hi, thanks for using Notiflix.

Notiflix Report module doesn't have any timeout property. The Report module elements doesn't disappear until their buttons were clicked. 

(May be you can manipulate it with a custom function to pretend a click event to the Report module buttons via a "setTimeout()" function or etc. if it necessary...)

Feel free to look at the documentation. 

Thanks.

**Comment by skamransajjad** [comment]
> perty is not workin

The timeout property is not working when using notify also
