### ISSUE TITLE
Notiflix.Notify | Ambiguous functionality: closeButton and autoClose 

### ISSUE THREAD

**Issue by sadedil** [notiflix/Notiflix#13]
Hi, we're using Notiflix (and we love it).

But, have a little problem. We just want to enable *closeOnClick* functionality for Notiflix.Notify methods, but can't simply succeeded.

* Firstly we tried to set `closeButton: true`, it worked but removed the auto-close functionality (and we don't understand why?) (Problem 1)

* Then, we realized when we set a `callback` method for Success / Info etc. It works like "click on close = true". So we add an empty callback methods for all calls `() => null` (Problem 2: This is a hack)

In my opinion, a simple *closeOnClick* property  like `Notiflix.Notify.Init({ closeOnClick: true })` could solve all complexity for this simple task.

**Comment by sadedil** [comment]
Actually I realized now, adding callback also blocking the auto-close feature. So I need a quick workaround to run this two features together:
* auto close
* close on click

**Comment by furcan** [comment]
Hi, firstly thanks for using Notiflix.

Like you realized; the Notify module designed to remove auto, except if has a callback function or the close button activated via options.

I notted your request. Notiflix V2 coming soon and this request probably will be added to the Notify module.

Thanks.

**Comment by furcan** [comment]
Hi, again...

Notiflix "v2" is ready to use.

This version includes a new module name as "Block".

"Notiflix.Block.*" module can be used to block or unblock elements to prevents users actions during the process (AJAX etc.) without locking the browser or the other elements.

Added: The "Block" module added to Notiflix.

Added: The "clickToClose" option added to the "Notiflix.Notify.*" module. Default is "false". This option can be set as "true" to remove each notification without waiting for it to be automatically removed when it has been clicked.

Changed: Code Review.
