### ISSUE TITLE
In the same page, I want to use Notiflix.Loading 2 times, but can't open the second after I remove the first 

### ISSUE THREAD

**Issue by iamwinter** [notiflix/Notiflix#14]
In the same page, I want to use Notiflix.Loading 2 times, but can't open the second after I remove the first .
for example:
```
Notiflix.Loading.Init();
Notiflix.Loading.Hourglass('the first loading');
//do something, about 5 seconds.
Notiflix.Loading.Remove();
Notiflix.Loading.Circle('the second loading!');
```
When the first loading was remove, the second loading did not open.
How can I do?
Thank you very much for answering my question!

**Comment by furcan** [comment]
Hi, firstly thanks for using Notiflix.

If you want to use the Loading module repeatedly, you have to wait to remove the first one. Then you can call the second one. 

And;
Notiflix Loading module has CSS animation to show or hide indicators. The default animation duration is 400 milliseconds.

So;
You have to delay your second call at least 400ms. (Or you can disable CSS animations for the Loading module.)

a simple example
```
Notiflix.Loading.Hourglass('the first loading');

// do something, about 5 seconds.

Notiflix.Loading.Remove();

var timeout = setTimeout( function() { 
   Notiflix.Loading.Circle('the second loading!');
}, 500);
```

_Tip: You do not have to initialize Notiflix modules if you want to use default settings. You can use them directly._
