### ISSUE TITLE
How to go on new line in Notiflix.Report.Info

### ISSUE THREAD

**Issue by iamwinter** [notiflix/Notiflix#15]
I wanna the text go on the next line, but '\n' is not correct way.
For Example,
```
var text="1. something;\n 2. something;\n 3. something;";
Notiflix.Report.Info( 'Title', text, 'OK');
```
The '\n' can't make a new line. 
Is there another way to make a new line?
Thanks a million for your help!

**Comment by furcan** [comment]
Hi,
Firstly thanks for using Notiflix.

There are many ways to add a new line to the Notiflix Report module.

A simple one is:

1- Initialize the Report module with this option. (Please free to look at the documentation for more information about the "plainText" option.)

```
Notiflix.Report.Init({
  plainText: false,
});
```

2- Add new lines using the `<br>` tag.

```
var message = '1- Line one <br>2- Line two <br>3- Line three...';

Notiflix.Report.Info('Title', message, 'Ok');
```

Thanks.
