### ISSUE TITLE
Hide the report icon

### ISSUE THREAD

**Issue by vmusulainen** [notiflix/Notiflix#16]
I need to hide the icon for the Report.
I  found out a workaround that setting svgSize to 0 in the report options.

Are there any other ways?

**Comment by furcan** [comment]
Hi,
Firstly thanks for using Notiflix.

Like you said the "svgSize" option can solve this request.
You can set zero this option to hide Icon for the Report module.

```
Notiflix.Report.Init({
    svgSize: '0px',
});
```

Thanks.
