### ISSUE TITLE
Showing the report without message

### ISSUE THREAD

**Issue by vmusulainen** [notiflix/Notiflix#18]
I have tried to show the report without message and I get Ford words' citation

https://github.com/notiflix/Notiflix/blob/master/dist/Unminified/notiflix-2.1.3.js#L719

It's way for showing the report without message? Or it is possible to do it passing message args as string with one space character?

**Comment by furcan** [comment]
Hi,
Firstly thanks for using Notiflix.

The message parameter is required for the Report module. 
You can define a string with one space character as you said for this request.

```
Notiflix.Report.Failure(
    'Title',
    ' ',
    'Button Text',
);

```
Thanks.
