### ISSUE TITLE
 I have a question in the confirm function.

### ISSUE THREAD

**Issue by worjs320** [notiflix/Notiflix#19]
hi nice to meet you.

first, I am using notiflix very well. thank you.

When the confirm popup open, 
How to make the popup close automatically when i press enter button?
Is there a way to set a HotKey?

**Comment by furcan** [comment]
Hi,

Firstly thanks for using the Notiflix, and glad to hear that works well for you.

Notiflix Confirm module has not any keypress listener to open or close it.

But you can create your own solution additionally and use it with the Notiflix Confirm module. 

An example is below. I used the only JavaScript for it, and you can take and use this approach with any of the 3 party libraries as jQuery or etc. for less code as you wish.

```
var notiflixKeypressListener = function kyprss(e) {
  // enter key code
  var enterKeyCode = 13;

  // get ok button
  var NXConfirmButtonOk = window.document.getElementById('NXConfirmButtonOk'); // This ID has been defined in the Notiflix Confirm module already.

  // or get cancel button
  // var NXConfirmButtonCancel = window.document.getElementById('NXConfirmButtonCancel'); // This ID has been defined in the Notiflix Confirm module already.

  // example for ok button (you can also take this approach for No button)
  if (e.keyCode === enterKeyCode && NXConfirmButtonOk) { // if pressed enter and if ok button exist
    // trigger ok button when pressed enter
    NXConfirmButtonOk.dispatchEvent(new Event('click'));
  }
};

var notiflixConfirmWithKeypressEvent = function nxCnfrm() {
  // add event listener
  window.document.addEventListener('keypress', notiflixKeypressListener);
  Notiflix.Confirm.Show(
    'Title',
    'Description',
    'Yes',
    'No',
    function yesCallback() {
      // your code when pressed to yes button
      console.log('Pressed for Yes');

      // remove keypress listener
      window.document.removeEventListener('keypress', notiflixKeypressListener);
    },
    function noCallback() {
      // your code when pressed to no button
      console.log('Pressed for No');

      // remove keypress listener
      window.document.removeEventListener('keypress', notiflixKeypressListener);
    },
  );
};
```

**Comment by worjs320** [comment]
thank you very much,

but, I want to modify the library file directly.
And I want to use the commands I used.

Thank you.

**Comment by worjs320** [comment]
> Hi,
> 
> Firstly thanks for using the Notiflix, and glad to hear that works well for you.
> 
> Notiflix Confirm module has not any keypress listener to open or close it.
> 
> But you can create your own solution additionally and use it with the Notiflix Confirm module.
> 
> An example is below. I used the only JavaScript for it, and you can take and use this approach with any of the 3 party libraries as jQuery or etc. for less code as you wish.
> 
> ```
> var notiflixKeypressListener = function kyprss(e) {
>   // enter key code
>   var enterKeyCode = 13;
> 
>   // get ok button
>   var NXConfirmButtonOk = window.document.getElementById('NXConfirmButtonOk'); // This ID has been defined in the Notiflix Confirm module already.
> 
>   // or get cancel button
>   // var NXConfirmButtonCancel = window.document.getElementById('NXConfirmButtonCancel'); // This ID has been defined in the Notiflix Confirm module already.
> 
>   // example for ok button (you can also take this approach for No button)
>   if (e.keyCode === enterKeyCode && NXConfirmButtonOk) { // if pressed enter and if ok button exist
>     // trigger ok button when pressed enter
>     NXConfirmButtonOk.dispatchEvent(new Event('click'));
>   }
> };
> 
> var notiflixConfirmWithKeypressEvent = function nxCnfrm() {
>   // add event listener
>   window.document.addEventListener('keypress', notiflixKeypressListener);
>   Notiflix.Confirm.Show(
>     'Title',
>     'Description',
>     'Yes',
>     'No',
>     function yesCallback() {
>       // your code when pressed to yes button
>       console.log('Pressed for Yes');
> 
>       // remove keypress listener
>       window.document.removeEventListener('keypress', notiflixKeypressListener);
>     },
>     function noCallback() {
>       // your code when pressed to no button
>       console.log('Pressed for No');
> 
>       // remove keypress listener
>       window.document.removeEventListener('keypress', notiflixKeypressListener);
>     },
>   );
> };
> ```

execuse me?

**Comment by furcan** [comment]
> thank you very much,
> 
> but, I want to modify the library file directly.
> And I want to use the commands I used.
> 
> Thank you.

Hi again, 

If you want to modify the Confirm module please feel free to fork it.

Thanks.
