### ISSUE TITLE
Confirm plaintext option

### ISSUE THREAD

**Issue by jczerosb** [notiflix/Notiflix#2]
What about give to Confirm same 'plainText: true/false' option as available on Report?

**Comment by notiflix** [comment]
Hi, first of all thank you for using Notiflix.

Your advice has been noted.

The next update to Notiflix will include this.

Thank you.

**Comment by notiflix** [comment]
Hello again.

Good news for you: Notiflix @1.3.0 released.  

The "plainText" option can use on the Confirm and the Notify modules now as in the Report module.

Thank you.

Note: You have to set the "plainText" options as "false" to use HTML allowed contents. Default values are "true" and not allowed HTML.

Example of usage for you:
`Notiflix.Confirm.Init({
plainText: false,
});`
