### ISSUE TITLE
SOLVED: how to close or dismiss previous notify 

### ISSUE THREAD

**Issue by suryansh4u** [notiflix/Notiflix#20]
i want to show only one notify at one time on page, when appear new notify previous notify automatically  close

**Comment by furcan** [comment]
Hi, 

Firstly thanks for using the Notiflix.

You can use the "showOnlyTheLastOne" option for this request.

Also, please feel free to look at the documentation page for this and all other options for the Notify module.
https://www.notiflix.com/documentation/#DocsNotify

So;
You can initialize first as below.
```
Notiflix.Notify.Init({
  showOnlyTheLastOne: true,
});
```

Thank you.
