### ISSUE TITLE
blur background text !

### ISSUE THREAD

**Issue by suryansh4u** [notiflix/Notiflix#21]
how to blur background text while Notiflix Loading is active ???

This can also be done in this way:---
https://leerob.io/static/images/loading-placeholder-with-sass/example.gif

**Comment by furcan** [comment]
Hi,
Firstly thanks for using the Notiflix.

There is not an option to blur the background for any of Notiflix module.

Thanks.

---

Additionally;

You can use the `backdrop-filter` property (CSS) to blur any of the backgrounds.

So you can write a custom CSS for the Loading module as below.

```css
div#NotiflixLoadingWrap {
    backdrop-filter: blur(0.5rem);
}
```

Also, please feel free to visit: 
https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter
