### ISSUE TITLE
Confirm dialog will appear again when go to the same page 

### ISSUE THREAD

**Issue by nyrf** [notiflix/Notiflix#23]
Thanks for your great library.

![Kapture 2020-05-23 at 3 22 49](https://user-images.githubusercontent.com/299532/82703138-f4decb00-9ca5-11ea-9394-0829fe94533e.gif)

**Comment by furcan** [comment]
Hi,

Firstly thanks for using the Notiflix.

Could you please share an example of the code about this. 
I can not get the issue by this GIF so I can not reproduce it.

Thank you.

**Comment by nyrf** [comment]
@furcan Sorry, i found out it was caused by turbolinks. i've add the codes and it works fine now, thanks.

```js
  document.addEventListener('turbolinks:before-cache', () => {
      if ($('#NotiflixConfirmWrap').length > 0) {
        $('#NotiflixConfirmWrap').remove()
      }
  }
```

**Comment by furcan** [comment]
@nyrf hi again,

All Notiflix modules have CSS animations to show or hide(also remove) themselves.

So, the Confirm module has 300 milliseconds of delay (`cssAnimationDuration`, you can look at the documentation page for more info). 
I think your navigation tool changing the route before the Confirm module removed. 

Probably your solution works fine, but I can recommend adding a timeout function to the Confirm module callback function to wait for removed.

Just an example:

```js
 Notiflix.Confirm.Show( 
    'Notiflix Confirm', 
    'Do you agree with me?', 
    'Yes', 
    'No', 
    function(){ // Yes button callback 
  
        var ruotingTimeout = setTimeout(function(){ 
          
            // your turbolink codes etc...

            clearTimeout(ruotingTimeout);
        }, 360); // => delay removing the Confirm module.
        
    }, 
    function(){ 
        // No button callback 
    } 
); 
```
