### ISSUE TITLE
Loading clickToClose option set to false, how to close it ? 

### ISSUE THREAD

**Issue by superawdi** [notiflix/Notiflix#26]
I have looked into the documentation and once you set the "**clickToClose**" option to false, there is no explanation of how to close it manually. So I am just using a plain javascript to remove it from "document.body".
I think it would be easier and better to return a closing function when you initialize a Loading :).

**Comment by furcan** [comment]
Hi @superawdi 

You can visit the link below to see how you can use the Loading module (add or remove etc.)

[Notiflix.Loading](https://github.com/notiflix/Notiflix#4--loading-module)

Also, the `clickToClose` is an optional setting to remove the loading indicator when it has been clicked and so, has been set as false to default. So, this option is not about the main removing approach to the Loading module.

Feel free to look at the link I already sent above.

Thanks.

Thanks.
