### ISSUE TITLE
Receiving data from the keyboard

### ISSUE THREAD

**Issue by aycanozarpaci** [notiflix/Notiflix#31]
Hello, first of all I was very happy that the library was developed by a human:) It would be nice to have a prompt for keyboard input. Do you think for a close version?

**Comment by furcan** [comment]
Hi @aycanozarpaci 

Firstly, thanks for using Notiflix.

About your first comment; maybe you may visit [CODE OF CONDUCT / Our Pledge](https://github.com/notiflix/Notiflix/blob/master/CODE_OF_CONDUCT.md#our-pledge) page to update your definition.

By the way, I did not get the point that you have mentioned: "to have a prompt for keyboard input".
Could you please describe your expectation a little bit more?

Thanks in advance.
Furkan.
