### ISSUE TITLE
[FEAT] - TS7016: Could not find a declaration file for module 'notiflix'

### ISSUE THREAD

**Issue by tungChasqui** [notiflix/Notiflix#34]
**Is your feature request related to a problem? Please describe.**
I don't want to always have to use `// @ts-ignore` with your library

**Describe the solution you'd like**
Please add @types/notiflix

**Describe alternatives you've considered**
Currently only use // @ ts-ignore or write a separate interface for it

**Additional context**
![image](https://user-images.githubusercontent.com/72437562/113476311-f3288b00-94a4-11eb-8c32-c17994d5a9cd.png)

**Comment by furcan** [comment]
Hi @tungChasqui 

Notiflix v2.8.0 will be released asap and the TypeScript declaration will be included. 

I will update this ticket when it has been released.

Thanks.

Furkan.

**Comment by furcan** [comment]
Hi @tungChasqui 

Notiflix v3.0.1 has released. TypeScript Declaration has included.

Also, this is a `Major` version. So, please take a look at the [CHANGELOG](https://github.com/notiflix/Notiflix/blob/main/CHANGELOG.md) to prevent the possible causes.

Thanks,
Furkan.
