### ISSUE TITLE
[BUG] - help me 

### ISSUE THREAD

**Issue by PandaStoremc** [notiflix/Notiflix#35]
I can't use html tag in notiflix report

**Comment by furcan** [comment]
Hi @PandaStoremc ,

HTML tags are not allowed as default. You can extend your global init as below.

```js
Notiflix.Report.Init({
  plainText: false,
});
```

Also, these links might be helpful for further info:
https://github.com/notiflix/Notiflix#2--report-module
https://github.com/notiflix/Notiflix#notiflix-report-module-default-options
https://www.notiflix.com/documentation/#DocsReport
