### ISSUE TITLE
How to set global style ? 

### ISSUE THREAD

**Issue by orhanmusellim** [notiflix/Notiflix#36]
Thanks for this libraries.

 I need to set global style changes, eg. change Success Notify background color. 

Thanks.

**Comment by furcan** [comment]
Hi @orhanmusellim 

You can use the `Init()` functions to do that. An example of usage is below.

```js
Notiflix.Notify.Init({
  success: {
    background: 'green',
  },
});
```

Also, these links might be helpful.
https://github.com/notiflix/Notiflix#1--notify-module
https://github.com/notiflix/Notiflix#notiflix-notify-module-default-options
https://www.notiflix.com/documentation/#GenNotify

Thanks.
Furkan.

**Comment by VictorPietro** [comment]
Hi @furcan, thanks for the help. I don't know exactly where should I put the `Notiflix.Notify.Init()` function so it applies globally.

I've tried to put it inside my `_app.tsx_` file, right before the `return`, but it didn't work. Do you know where should I put it? This is a NextJS project.
