### ISSUE TITLE
change default notify icon

### ISSUE THREAD

**Issue by alimatinfar** [notiflix/Notiflix#38]
hello
how can i change the default notify icon ?

**Comment by furcan** [comment]
Hi @alimatinfar ,

You can init/call the Notify module like an example below to use custom icons. (font-awesome or the equivalent web fonts)

```js
Notiflix.Notify.success({
  useIcon: true, // default is true
  useFontAwesome: true, // default is false
  success: {
    fontAwesomeClassName: 'fab fa-github', // font-awesome icon class name...
  },
});
```

Also, you can take a look at the all other options as well.
https://github.com/notiflix/Notiflix#notiflix-notify-module-default-options

Thanks,
Furkan.

**Comment by alimatinfar** [comment]
can i use custom svg in notify?

**Comment by furcan** [comment]
Hi,
Unfortunately, you can't.
Thanks.
Furkan.
