### ISSUE TITLE
Dismiss/Overlay

### ISSUE THREAD

**Issue by origranot** [notiflix/Notiflix#4]
Hey, I didn't saw that you have a feature to dismiss other notifications.
If I generate two notification one after another, is there a way to display only the last one clicked?

**Comment by furcan** [comment]
Hi there,

Firstly thanks for using Notiflix.

Unfortunately, that's not possible for the Notiflix Notify module. It's designed to show all notifications you have triggered.

And I noted your request. Probably the next update may include this new option. 

The new option could be: "showOnlyLastOne: false,"

You can also set this option as "true" to show only the last notification triggered by the Notify module.

Thank you.

**Comment by furcan** [comment]
Hi again.

Notiflix v1.8.0 released yet and "showOnlyTheLastOne" option added to the "Notiflix Notify" module.

Default value is "false". You can change this option as "true" to show only the last notification.

Thanks.

https://github.com/notiflix/Notiflix/blob/master/ReleaseNotes.md
