### ISSUE TITLE
notifilix-react NPM Package Not found

### ISSUE THREAD

**Issue by MertDemirok** [notiflix/Notiflix#40]
notifilix-react package's not found, Anyone know why it was removed?

So Old version removed

Url :https://www.npmjs.com/package/notiflix-react

**Comment by furcan** [comment]
Hi,
You can use this repository/package as well instead of the non existing one.
Thanks.

```sh
# yarn 
yarn add notiflix 

# npm
npm i notiflix
```

**Comment by furcan** [comment]
Hi @MertDemirok,

Could you please give some feedback if you have solved the issue? 

Thanks.
