### ISSUE TITLE
When there's a Report opened it's still possible to navigate the page using the Tab key

### ISSUE THREAD

**Issue by RavazziniAndrea** [notiflix/Notiflix#41]
**Describe the bug**
As said in the title, whenever there's a Report opened in fullscreen, the page is still navigable using the Tab key and with the Enter key links are still clickable.

**Expected behavior**
In my opinion, the report has to be closed by pressing che Enter key and the Tab has to be blocked in the mean time.

**Desktop:**
 - OS: Linux Mint 20.2
 - Browser: Firefox 91.0.1esr , Chromium 92.0.4515.159

**Comment by furcan** [comment]
Hi @RavazziniAndrea ,

Notiflix is a non-blocking notification library. So, this library can not predict which events and/or elements should be prevented and/or blocked.

You have to create your own solution/approach to prevent and/or block the events/elements.

An example is below.

```js
var blockThem = function () {
    // your codes...
};

var unblockThem = function () {
    // your codes...
};

// ---
// ---
// ---

blockThem();
Notiflix.Report.info(
    'Title',
    'Description',
    'Button Text',
    // Button onClick callback func
    function cb() {
        unblockThem();
    },
);
```

Thanks,
Furkan.
