### ISSUE TITLE
[FEAT] - Add Prompt Dialog

### ISSUE THREAD

**Issue by ERROPiX** [notiflix/Notiflix#42]
**Is your feature request related to a problem? Please describe.**
Yes, the `Notiflix.Confirm.ask()` function doesn't allow the user to provide answers other than the defined correct answer.

**Describe the solution you'd like**
 If you can change the library to accept any value and pass it to the button callbacks, it will serve as an equivalent for the native browser prompt.

**Describe alternatives you've considered**
The native browser prompt https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_prompt

**Comment by furcan** [comment]
Hi @ERROPiX ,

Thanks for the suggestion, 

I will consider adding a new method (e.g. the method name could be "`prompt()`") to the Confirm module for this request in the next minor/major update.

Thanks,
Furkan.

**Comment by furcan** [comment]
Hi @ERROPiX 

Notiflix v3.2.0 has been released.
https://github.com/notiflix/Notiflix/releases/tag/v3.2.0

You can use `Notiflix.Confirm.prompt();` method for this request.

Thanks,
Furkan.

**Comment by ERROPiX** [comment]
Thank you so much @furcan for the quick update :)

**Comment by furcan** [comment]
Hi @ERROPiX ,

You are welcome 😊 

Have a nice week,
Furkan.
