### ISSUE TITLE
Click on the overlay to close the popup

### ISSUE THREAD

**Issue by hieuvume** [notiflix/Notiflix#48]
In the Report feature, you can add a feature that allows the user to click on the overlay to close the popup.
You can add a boolean prop to turn this feature off or on

**Comment by furcan** [comment]
Hi @hieuvume ,

I already thought about using that kind of feature for the background overlay before. And then, I decided to not add this feature. 

Background overlay is an option that can be switched off as you can see (`backOverlay: true`). And maybe another option can be added as well to removing the Report Boxes as you have recommended with a click event. 

I will consider this for the next updates.

Thanks.
Furkan.

**Comment by hieuvume** [comment]
I'm looking forward to this. Hopefully it will be in the next update soon

**Comment by furcan** [comment]
Hi @hieuvume,

v3.2.5 has been released.

https://github.com/notiflix/Notiflix/blob/main/CHANGELOG.md
