### ISSUE TITLE
How to implement in Angular8

### ISSUE THREAD

**Issue by tmbeamm** [notiflix/Notiflix#5]
I want to implements to Angular 8 
It not working

**Comment by furcan** [comment]
Hello,

Unfortunately, this version of Notiflix is not able to use with Angular.

You can follow the repository below for use Notiflix with Angular.

https://github.com/notiflix/Notiflix-Angular

It is coming soon.

Thanks.

**Comment by furcan** [comment]
Hi again,

You can use Notiflix in Angular with the repository below:
https://github.com/notiflix/Notiflix-Angular

Thanks.

**Comment by DDriggs00** [comment]
@furcan The linked repository is archived. Does that mean that angular support has ended, or is there another way to use notiflix with angular?

**Comment by furcan** [comment]
Hi @DDriggs00 

You can use this repository :] 

Thanks.
