### ISSUE TITLE
[FEAT] - Custom icon on all modules

### ISSUE THREAD

**Issue by ScoopAndrun** [notiflix/Notiflix#53]
First, thank you for this excellent and simple library.

### Is your feature request related to a problem? Please describe.
No. Preset icons do not cause any issue but sometimes do not fully represent the meaning of the message to the user.

### Describe the solution you'd like
Just like the Notify module allows us to use a custom Font Awesome icon, the possibility to customize the icon for all modules would be very nice.  
Also, maybe add the possibility to use other icon sets (like [Material Icons](https://fonts.google.com/icons?selected=Material+Icons), [Bootstrap Icons](https://icons.getbootstrap.com/), etc.)?

### Describe alternatives you've considered
At the moment, use of the default icon seems to be the only simple solution, although it seems possible to change the icon with JavaScript.

**Comment by furcan** [comment]
Will be considered in v4.
Thanks.
