### ISSUE TITLE
[FEAT] - ES6 Module Support

### ISSUE THREAD

**Issue by KyGost** [notiflix/Notiflix#54]
The ability to use this library with module support in ES6 would be great.
As I understand (though I am far from immersed in the technology), most other module systems support ES6 modules.

This would enable faster, more efficient, more simple loading for Vanilla usage of this library.

**Comment by furcan** [comment]
https://github.com/notiflix/Notiflix/issues/52#issuecomment-1128798471

**Comment by KyGost** [comment]
> [#52 (comment)](https://github.com/notiflix/Notiflix/issues/52#issuecomment-1128798471)

That doesn't provide any information on ES6 module usage?
I see usage via Yarn, NPM & window but not ES6 module.
