### ISSUE TITLE
dont disappear when it is hoverd

### ISSUE THREAD

**Issue by alireza95jalili** [notiflix/Notiflix#6]
Hi, is any way, if a notif is hovered, we can do pause the timeout and disappearing until the mouse move out of the notify box?

**Comment by furcan** [comment]
Hi,
Firstly thanks for using Notiflix.

Unfortunately, that's not possible yet.

And I noted your request. Probably the next updates may include this new option.

In the meanwhile, you maybe want to use the "closeButton" option. This option default value is "false". If you can set this option as "true", the Notify module notifications with the close button will not disappear until they were clicked.
You can visit the Documentation page to learn more about this option.

Thank you.
