### ISSUE TITLE
[BUG] - call confirm after prompt

### ISSUE THREAD

**Issue by injaan** [notiflix/Notiflix#60]
### Describe the bug
I called confirm window after successful prompt action but confirm not called, nothing happened

### To Reproduce
call confirm after prompt

### Desktop (please complete the following information):
 - OS: [e.g. Windows, macOS...]
 - Browser [e.g. Chrome, Edge, Firefox, Safari...]
 - Version [e.g. v3.0.0]

### Smartphone (please complete the following information):
 - Version [e.g. v3.0.0]

**Comment by furcan** [comment]
Hi @injaan 

Can you please share your snippet to see what is happening? 

---

In addition: 
You need to be sure that the previous Confirm method should be removed(there is a CSS animation delay(of 300 milliseconds), so it is not removed immediately) from DOM. 

The Confirm module is allowing to show only one confirmation at the same time.  This means you will not get the second one if you are calling the second one before the previous one is completely removed.

**Comment by injaan** [comment]
Hi @furcan thank you for answered for my problem
I tried following
```
Confirm.prompt(
    'Are you sure',
    'Please enter number!',
    '10',
    'Continue',
    'Cancel',
    (value) => {
        if(value){
            Confirm.show(
                'Confirm',
                `Your chosen number is ${value} are you sure to continue?`,
                'Yes',
                'No',
                () => {
                  console.log("confirmed", value);
                }
              );
        }
    }
);
```

So is it really not possible to call 'Confirm' right after 'Prompt'? I think call confirm after prompt would be really useful if it is implemented.

**Comment by furcan** [comment]
Hi @injaan 

This is your solution.

Thanks.

```js
var delay = 300; // the default value

Confirm.prompt(
  "Are you sure",
  "Please enter number!",
  "10",
  "Continue",
  "Cancel",
  (value) => {
    if (value) {
      const wait = setTimeout(function () {
        Confirm.show(
          "Confirm",
          `Your chosen number is ${value} are you sure to continue?`,
          "Yes",
          "No",
          () => {
            console.log("confirmed", value);
          }
        );
        clearTimeout(wait);
      }, delay + 1);
    }
  },
  undefined,
  {
    cssAnimationDuration: delay,
  },
);
```

**Comment by injaan** [comment]
@furcan thank you

**Comment by furcan** [comment]
You are welcome 🙏
