### ISSUE TITLE
[BUG] - Long message getting cut off on Report. Implement scrolling?

### ISSUE THREAD

**Issue by polis80cy** [notiflix/Notiflix#62]
### Describe the bug
I am using `Report.Success` with a long message. Is there a way to implement scrolling? Currently, it gets cut off. I didn't see anything relevant in the available properties.

### Screenshots
![Screenshot 2023-01-13 at 12 48 24 PM](https://user-images.githubusercontent.com/14854276/212302185-7061db71-e98b-4a2b-8e46-5bd03e0960c1.png)
![Screenshot 2023-01-13 at 12 48 34 PM](https://user-images.githubusercontent.com/14854276/212302274-5c7a23e5-d587-461c-a371-b363dbbd27a3.png)

**Comment by furcan** [comment]
Hi @polis80cy 

```js
Notiflix.Report.success(
  'Code explanation',
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  'Okay',
  function cb() {
    alert('Okay');
  },
  {
    messageMaxLength: 123456, // as you wish...
  },
);
```

Please feel free to take a look at the documentation as well.
https://notiflix.github.io/documentation#DocsReport

Thanks.
