### ISSUE TITLE
[BUG] - Notify.success() -> Can it stay visible until an async operation completes, similar to Notify.Loading?

### ISSUE THREAD

**Issue by polis80cy** [notiflix/Notiflix#64]
### Describe the bug
As per the title, can `Notify.success()` behave like `Notify.Loading`, i.e. stay visible until we call `Loading.remove()`?

In other words, do we have any control over the duration `Notify.success` is visible? Adding a fixed `delay` is not what I need since I need `Notify.success` to remain visible for as long as an async operation is running.

**Comment by furcan** [comment]
Hi,

Notify and Loading modules are completely different and unrelated. If you are expecting the Notify module working like Loading one, it is related to your implementation, not related to this library.

Notiflix is an open-source library. You can fork and extend as you wanted.

Thanks.
