### ISSUE TITLE
[BUG] - confirm stack

### ISSUE THREAD

**Issue by smisyuk4** [notiflix/Notiflix#74]
### Describe the error
Two confirmations in a row do not work

### To play
1. Create one

Confirm.prompt(
      'Reauthorization',
      'Please enter your password',
      '',
      'Send',
      'Cancel',
      answer => {
        setPassword(answer);
      },
      () => {},
      {}
    );
  };

2. Create a second one

Confirm.show(
      'Profile deletion!',
      'Really delete?',
      'So',
      'No',
      () => {
      },
      () => {}
    );

### Expected behavior
I expected that first there would be one modal window and I would enter the data, then I would get a message about deleting the profile and an option to confirm it

**Comment by furcan** [comment]
https://github.com/notiflix/Notiflix/issues/60

Thanks
