### ISSUE TITLE
[BUG] - Notify position doesn't work

### ISSUE THREAD

**Issue by rafaelpoa** [notiflix/Notiflix#77]
I'm using version 3.2.6 and in notify the position option isn't working, even if I change it to the suggested ones nothing happens. It always remains in the default position. I'm using reactjs and loading Init correctly, as all other options work fine.

**Comment by furcan** [comment]
Hello

Please share your implementation(Notifilix parts) as a code snippet or please provide a codesandbox example. And reopen this ticket again.

Thanks,
Furkan
