### ISSUE TITLE
[BUG] - CommonJS or AMD dependencies can cause optimization bailouts

### ISSUE THREAD

**Issue by johnbendi** [notiflix/Notiflix#78]
### Describe the bug
Using notiflix from  an Angular project throws the above warning message

### To Reproduce
1. Create an Angular version 15 component.
2. Import Confirm or Block from Notifix
3. Use Confirm or Block in the code
4. Save the file
5. Compile the file to get the warning message: Component depends on 'notiflix'. CommonJS or AMD dependencies can cause optimization bailouts

### Expected behavior
Component should compile without warning 

### Desktop (please complete the following information):
 - OS: Linux
 - Browser [N/A]
 - Version [v3.2.6]

### Smartphone (please complete the following information):
 - Device: [N/A]
 - OS: [N/A]
 - Browser [N/A]
 - Version [N/A]

### Additional context
None.

**Comment by furcan** [comment]
Hello.

It is obvious that this package is not your package if you are considering ESM.

Notiflix uses UMD and works everywhere if window exist.

You can please ignore this development time error or please use another library.

Thanks,
Furkan
