### ISSUE TITLE
[FEAT] - is the Notify can remove?

### ISSUE THREAD

**Issue by langziyang** [notiflix/Notiflix#79]
like Loading.remove() but need specify id;

Notify.success('message',{
  id:'some_id'
})

then 
Notify.remove('some_id')

**Comment by furcan** [comment]
Hello,

The Notify module is designed to be removed automatically after some delay or to be removed after clicking if there is a callback assigned.

I will take your expectations as a note for future major updates.

Thanks,
Furkan
