### ISSUE TITLE
[FEAT] - Function to close all open toast with notify

### ISSUE THREAD

**Issue by simonebosio91** [notiflix/Notiflix#84]
### Is your feature request related to a problem? Please describe.
In my portal today I have the problem that when I log out and return to the login, if there are any toast with notify from the session they remain on the screen even on the login page.

### Describe the solution you'd like
It would be nice to have a function that can be easily called on logout that closes all open toast 

### Describe alternatives you've considered
To date, the only solution is to save the popup id when it is opened, within the session storage and then at logout cycle them and then close them

**Comment by furcan** [comment]
Hello,

Could you please share a screen record or something regarding what is happening and what is expected?
Then I can consider this improvement or maybe it is not applicable or maybe it is implementation specific and shouldn't be in the library and so on...

Best wishes,
Furkan
