### ISSUE TITLE
[FEAT] - Adding a checkbox/radio in Confirm?

### ISSUE THREAD

**Issue by gensart-x** [notiflix/Notiflix#86]
### Is your feature request related to a problem? Please describe.
Sometimes when confirming some action, like deleting an item, I need to add an option for the user to delete another item that references that.

### Describe the solution you'd like
In a Notiflix.Confirm UI, it should be an element like a checkbox or something else.

### Describe alternatives you've considered
- _nothing on mind_

### Additional context
- _nothing on mind_

**Comment by furcan** [comment]
Hello,

Can be helpful: https://github.com/notiflix/Notiflix/issues/85

Thank you,
Furkan
